version: '3'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: one_final_node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  migration:
    image: migrate/migrate
    container_name: one_final_migrate
    command: "-path=/migrations -database=postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable up"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./migrations:/migrations
    networks:
      - one_network

  app:
    container_name: one_final_app
    build: .
    command: ["./main"]
    ports:
      - 8080:8080
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_KEY=${AUTH_KEY}
    volumes:
      - ./configs:/app/configs
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - one_network

volumes:
  db-data:

networks:
  one_network:
    driver: bridge